// src/client-vue/src/views/routes/ThreadView.vue
<template>
    <div>
        <v-row class="mt-15 mb-5" justify="center">
            <v-col>
                <v-row justify="center">
                    <v-pagination v-if="state.threads.pagination[threadId]" :value="state.threads.pagination[threadId].page" :length="state.threads.pagination[threadId].totalPages" @input="onPageChange" circle color="orange darken-1" />
                </v-row>
                
                <v-row justify="center" class="my-6">
                    <v-sheet min-width="50vw"
                            max-width="50vw">
                        <template v-for="t in threads">
                            <Thread v-if="threadId == threadConstants.all || threadId == threadConstants.self" 
                                    :key="t.id" 
                                    :thread="t" 
                                    @on-thread-click="onThreadClick"
                                    @on-upvote="onUpvoteThread"
                                    @on-downvote="onDownvoteThread"
                                    @on-delete="onDeleteThread" />
                            <ThreadMessage v-else 
                                            :key="t.id" 
                                            :message="t" 
                                            @on-upvote="onUpvoteMessage"
                                            @on-downvote="onDownvoteMessage"
                                            @on-delete="onDeleteMessage"
                                            @on-edit="onSaveMessage" />
                        </template>
                    </v-sheet>
                </v-row>

                <v-row justify="center">
                    <v-pagination v-if="state.threads.pagination[threadId]" :value="state.threads.pagination[threadId].page" :length="state.threads.pagination[threadId].totalPages" @input="onPageChange" circle color="orange darken-1" />
                </v-row>
            </v-col>
        </v-row>
        <ThreadDialog :mode="state.threads.mode" :disabled="state.user == null" @on-save="onSaveThread" :thread="thread" />
    </div>
</template>

<script>
    import state from '@/state'
    import actions from '@/actions'
    import Thread from '@/components/Thread'
    import ThreadMessage from '@/components/ThreadMessage'
    import LoginService from '@/services/loginService'
    import { thread as threadConstants } from '@/constants'
    import ThreadDialog from '@/views/dialogs/ThreadDialog'

    export default {
        name: 'ThreadView',

        components: {
            Thread,
            ThreadMessage,
            ThreadDialog,
        },

        data: () => ({
            threadId: '',
            threads: [],
            state,
            threadConstants,
            thread: {},
        }),

        watch: {
            $route() {
                this.initialize();
            },
        },

        methods: {
            initialize() {
                this.threadId = this.$route.params.id;
                let page = parseInt(this.$route.query.page) || 1;
                let existingPage = 0;

                this.thread = {
                    threadId: this.threadId,
                    title: state.threads.titles[this.threadId],
                };

                let threadPagination = state.threads.pagination[this.threadId];
                if(threadPagination) {
                    existingPage = threadPagination.page;
                    threadPagination.page = page;
                }

                let threads = state.threads.messages[this.threadId];
                if(threads) {
                    this.threads = [...threads];
                }

                document.title = `${state.threads.titles[this.threadId]} | Task Tracker`;

                let isEmpty = state.threads.messages[this.threadId] == null || state.threads.messages[this.threadId].length == 0 || page != existingPage;
                
                if(this.threadId == threadConstants.all) {
                    if(isEmpty) {
                        actions.threads.fetchAll().then(() => {
                            this.threads = [...state.threads.messages[this.threadId]];
                        });
                    }
                } else if(this.threadId == threadConstants.self && LoginService.isLoggedIn()) {
                    if(isEmpty) {
                        actions.threads.fetchSelf().then(() => {
                            this.threads = [...state.threads.messages[this.threadId]];
                        });
                    }
                } else if(this.threadId != threadConstants.all && this.threadId != threadConstants.self) {
                    if(isEmpty) {
                        actions.threads.fetch(this.threadId).then(() => {
                            document.title = `${state.threads.titles[this.threadId]} | Task Tracker`;
                            this.threads = [...state.threads.messages[this.threadId]];
                            this.$emit('on-tab-change', this.threadId);
                        });
                    } else {
                        this.$emit('on-tab-change', this.threadId);
                    }
                }
            },

            onThreadClick($event) {
                let thread = $event.thread;
                let page = 1;
                if(state.threads.pagination[thread.threadId]) {
                    page = state.threads.pagination[thread.threadId].page;
                }
                    
                this.$router.push(`/threads/${thread.threadId}?page=${page}`);
            },

            onUpvoteThread($event) {
                actions.threads.upvoteThread($event.thread.threadId);
            },

            onDownvoteThread($event) {
                actions.threads.downvoteThread($event.thread.threadId);
            },

            onUpvoteMessage($event) {
                actions.threads.upvoteMessage($event.message.threadId, $event.message.messageId);
            },

            onDownvoteMessage($event) {
                actions.threads.downvoteMessage($event.message.threadId, $event.message.messageId);
            },

            onDeleteThread($event) {
                actions.threads.removeThread($event.thread.threadId);
            },

            onDeleteMessage($event) {
                actions.threads.removeMessage($event.message.threadId, $event.message.messageId);
            },

            onSaveMessage($event) {
                actions.threads.modifyMessage($event.message.threadId, $event.message.messageId, $event.message.content);
            },

            onSaveThread($event) {
                if($event.mode == threadConstants.message) {
                    actions.threads.addMessage($event.item.threadId, $event.item.content);
                } else if($event.mode == threadConstants.thread) {
                    actions.threads.addThread($event.item);
                }
            },

            onPageChange(page) {
                this.$router.push(`/threads/${this.threadId}?page=${page}`);
            }
        },
        
        created() {
            state.$on('messages-changed', () => {
                this.initialize();
            })
            
            this.initialize();
        },

        destroyed() {
            state.$off('messages-changed');
        }
    }
</script>

<style scoped>

</style>

// src/client-react/src/views/routes/ThreadView.js
import React, { useCallback, useState, useEffect } from 'react'
import { Grid } from '@material-ui/core'
import { Pagination } from '@material-ui/lab';
import ThreadMessage from '../../components/ThreadMessage'
import Thread from '../../components/Thread'
import { thread as threadConstants, defaultPagination } from '../../constants'
import state from '../../state'
import actions from '../../actions';
import { useHistory } from 'react-router-dom'

export default function ThreadView(props) {
    const [pagination, setPagination] = useState(state.threads.value.pagination[props.threadId] || { ...defaultPagination });
    const history = useHistory();
    
    useEffect(() => {
        const sub = state.threads.subscribe(x => {
            setPagination(state.threads.value.pagination[props.threadId] || { ...defaultPagination });
        });

        return () => sub.unsubscribe();
    }, []);

    const onThreadClick = useCallback((thread) => {
        if(props.onThreadClick) {
            props.onThreadClick(thread.threadId);
        }
    }, []);

    const onUpvoteThread = useCallback((thread) => {
        actions.thread.upvoteThread(thread.threadId);
    }, [])

    const onDownvoteThread = useCallback((thread) => {
        actions.thread.downvoteThread(thread.threadId);
    }, [])

    const onUpvoteMessage = useCallback((message) => {
        actions.thread.upvoteMessage(message.threadId, message.messageId);
    }, []);

    const onDownvoteMessage = useCallback((message) => {
        actions.thread.downvoteMessage(message.threadId, message.messageId);
    }, []);

    const onDeleteThread = useCallback((thread) => {
        actions.thread.removeThread(thread.threadId);
    }, []);

    const onDeleteMessage = useCallback((message) => {
        actions.thread.removeMessage(message.threadId, message.messageId);
    }, []);

    const onSaveMessage = useCallback((data) => {
        actions.thread.modifyMessage(data.item.threadId, data.item.messageId, data.item.content);
    }, []);

    const onPageChange = useCallback((event, newPage) => {
        history.push(`/threads/${props.threadId}?page=${newPage}`);
        /*let paginations = { ...state.threads.value.pagination }
        paginations[props.threadId].page = newPage;

        state.threads.next({
            ...state.threads.value,
            pagination: paginations
        })

        let threadId = props.threadId;
        
        if(threadId == threadConstants.all) {
            actions.thread.fetchAll();
        } else if(threadId == threadConstants.self) {
            actions.thread.fetchSelf();
        } else if(state.threads.value.active.has(threadId)) {
            actions.thread.fetch(threadId);
        }*/
    }, [])


    return (
        <React.Fragment>
            <Grid item><Pagination count={pagination.totalPages} page={pagination.page} onChange={onPageChange} /></Grid>
            { 
                props.items ? 
                (
                    props.threadId == threadConstants.self || props.threadId == threadConstants.all ?
                    props.items.map((y) => 
                        <Grid item key={y.threadId}>
                            <Thread disabled={props.user == null} user={props.user} thread={y} onDelete={onDeleteThread} onThreadClick={onThreadClick} onUpvote={onUpvoteThread} onDownvote={onDownvoteThread} />
                        </Grid>) :
                    props.items.map((y) => 
                        <Grid item key={y.messageId}>
                            <ThreadMessage disabled={props.user == null} user={props.user} message={y} onDelete={onDeleteMessage} onUpvote={onUpvoteMessage} onDownvote={onDownvoteMessage} onSave={onSaveMessage} />
                        </Grid>)
                ) : 
                null 
            }
            <Grid item><Pagination count={pagination.totalPages} page={pagination.page} onChange={onPageChange} /></Grid>
        </React.Fragment>
    )
}
