// src/client-react/src/views/Error.js
import React from 'react'
import './Error.css'
import { Link } from 'react-router-dom'

export default function Error(props) {
    const error = props.meta;

    return (
        <div className="errorPage-body">
            <div className="errorPage-center">
                <div className="errorPage-title">
                    <div className="errorPage-errorImage"><img src={error.imageSrc} /></div>
                    <div className="errorPage-errorText">
                        { error.text }
                    </div>
                </div>
                <div className="errorPage-subTitle">
                    { error.subTitle }
                </div>
                <div className="errorPage-content">
                    { error.content }
                </div>
            </div>
            {
                !error.noRedirect ?
                <div className="errorPage-bottom">
                    Redirect to <Link to={error.redirectRoute}>{ error.redirectText || 'Login' } page</Link>
                </div> :
                null
            }
        </div>
    )
}

// src/client-vue/src/views/Error.vue
<template>
    <div class="errorPage-body">
        <div class="errorPage-center">
            <div class="errorPage-title">
                <div class="errorPage-errorImage"><img :src="error.imageSrc" /></div>
                <div class="errorPage-errorText" v-if="error.text">
                    {{ error.text }}
                </div>
            </div>
            <div class="errorPage-subTitle">
                {{ error.subTitle }}
            </div>
            <div class="errorPage-content">
                {{ error.content }}
            </div>
        </div>
        <div class="errorPage-bottom" v-if="!error.noRedirect">
            Redirect to <router-link :to="{ name: error.redirectRoute }">{{ error.redirectText || 'Login' }} page</router-link>
        </div>
    </div>
</template>

<script>
    import LoginService from '@/services/loginService'

    export default {
        name: 'Error',
        
        data() {
            return {
                error: this.$route.meta.data,
            }
        },

        created() {
            if(this.$route.meta.data.text == '401') {
                LoginService.logout(true);
            }
        }
    }
</script>

<style scoped>
    .errorPage-body {
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        color: #424242; 
        font-family: 'Helvetica';
        text-align: center;
        background-color: #ECEFF1;
        position: absolute;
    }

    .errorPage-center {
        position: absolute;
        left: 50%;
        top: 50%;
        -webkit-transform: translate(-50%, -50%);
        transform: translate(-50%, -50%);
    }

    .errorPage-bottom {
        position: fixed;
        bottom: 0;
        width: 100%;
        font-size: 18px;
        padding: 15px 0;
    }

    .errorPage-title {
        display: flex;
        flex-direction: row;
        font-size: 128px;
        justify-content: center;
        align-items: center;
    }

    .errorPage-errorImage {
        display: flex;
        width: 128px;
        height: 128px;
        margin-right: 14px;
    }

    .errorPage-errorText {
        display: flex;
        margin-left: 15px;
    }

    .errorPage-subTitle,
    .errorPage-content,
    .errorPage-bottom {
        color: #757575 !important;
    }

    .errorPage-subTitle {
        font-size: 40px;
        margin-top: 45px;
        margin-bottom: 30px;
    }

    .errorPage-content {
        font-size: 20px;
        margin-top: 12px;
    }

    a:link,
    a:visited,
    a:hover,
    a:active {
        color: #01579B;
    }
</style>
